site_name: Board
nav:
    - 'Home' : 'index.md'

    - 'Configuration Software': 'configuration-software.md'
    - 'Light communication' : 'light-communication.md'
plugins:
    - with-pdf:
        author: TheJades, GManAndMarbles
        #copyright: ANY TEXT
        #
        #cover: false
        #back_cover: true
        cover_title: Manual
        cover_subtitle: Whole Repo
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: pdf/manual.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true