site_name: Board
nav:
    - 'Home' : 'index.md'

    - 'Configuration Software': 'configuration-software.md'
    - 'Light communication' : 'light-communication.md'
    - 'Showbox ' : 'showbox.md'
#plugins:
#    - with-pdf:
#        author: TheJades, GManAndMarbles
#        cover_title: Manual
#        cover_subtitle: V1.0
#        output_path: pdf/manual.pdf

        